language: java
before_script:
- echo "Starting build"
script:
- mvn clean package
after_script:
- echo "Script finished"
after_succes:
- echo "Build ready"
- ls -l $TRAVIS_BUILD_DIR/target
after_failure:
- echo "Build failed"
deploy:
  provider: heroku
  api_key:
    secure: HdLASzwIetnRUqv6k/IQauuN0iCquAEUzfDxT0FQFZsdaLKiXoPLC+KlNx9JSbEX5wuzdRzQ7praFlfedjkJYZp3XBjghWKJrlRF3Ks7a43HA6jE6ADYb7cQjouL1Edptxx+2nLJsrhIwkiKOjymx9loepIT035NZGtdAj+LiCld9QrxW7m7lBbXtvSHOabKtTkinS5cSYySg5bHqg0g8TGVdpak9Azm0SjgcFqrZycPGW3AXZbxlPynngwWGAr/r75ml8iFrrjAUrwhUI3Za25Thd2xI5wFj1V0MCrhnOdwASD2FjVALj0tKUkDfEQfxGmB06plKSr+bjj9mMHDdtgtLg3d8plMeMOILqk3qaRAkTfTqh+XC+KC9TQ2zsOOy9jZaBxoRaqYkGJ9LeY9770jDZTeBNTcMM34HEevCCPiVnykWtzmLGGqIFZcgLmMmb9TY4Jg4GLwnLoCxsLO3Im/Xb9uD+rv/UxC9YcheUH5j0Q7sasQYxULlp7YF8bFKHvmysyDs+Njf/7PkllSIcEFIohP7Cf3pf3Mr9rhH2hXyc4KwXhWYMcaYrJqUYbZwl01e+HuPzckE03cw1cNvCYFj02rsXm0p+EvN/hI1U3fuQlvM8FYznxPWcXE3ZCFme4/PDX0qjFH6jd3MSP/Vo8a/UAsQOjq2QCSzLX+o30=
  app: test-shamuratov
