language: java
before_script:
- echo "Starting build"
script:
- mvn clean package
deploy:
  provider: heroku
  api_key: eFjhvjpYMtMkVV0AGAnpRhNEmoXG+L779R5BenKzm4vY9AWpnhv9Kqkmf5P8SC8AytcM/4k/ZuF0BQrs59LupfjuVJQAcFTWXlray9e7/rcyocglGIvXLvkinE/De0lBSsXZYQY5VQiOcSBXGyUth9kqKOrcrZ2fyTQE9yP8yVyicNKefa3gwOp81tJzYynrg1HTkO9jNvLeZlPfa2UynMgFVDy9EjKSRB09Wb7x0jdfoJBl7CESWjKWv44nZQImbAAOc7hnxXhI+D7INz6R4BihXfbbIvUYApw88pp71Y89OvQSSYRiB+e5uSrkRCdplGHF6WYI7ELaiCHwbbV1cqoiahdQFuQKapmnGh4Jzt/L03/CIzrC+iPzPYpxpyXyQdZtXCm2R6C/sHXyw29D0x9o6gQgYCt7RcZzArPsyBr4o4puv5AYvpM/qbXrCFPiZdan0S/Z1zDQFqIVfk7m+ixFPXxm70Hf4Fsdn5GsSh5ez6uOQf3W3ZjQZEJac43tqG0IEm/dAoY1TxbAITuu3N1S8s5/xYuGg0QME01J/HYYpX3yBLE8YTxVYlXFrtAWe9ILifPuB4mqsv1a11w0Ms/AONwBTLoXIWhd53/ADu+OM+29ksXPWzXE1ZRTyh0buyNemKi0onYN96AxK9XxQqVXVVqZdSwq73f0/aAKwtE=
  app:
    master: test-shamuratov
